# XGBoost Stability Portfolio Configuration
# Optimized settings based on best individual test results

# Target configuration
target_symbol: "@ES#C"
start_date: "2015-01-01"
end_date: "2025-08-01"

# XGBoost model settings
n_models: 100
xgb_type: "standard"  # or "deep" for more complex models
binary_signal: false  # Use continuous signals for better Sharpe
max_features: -1      # Use all selected features
rolling_training: false
rolling_window: 504

# Rolling window configuration
start_train: 750     # Initial training period (3 years)
step: 21            # Rebalancing frequency (monthly)
horizon: 21         # Out-of-sample horizon (monthly)
inner_val_frac: 0.2 # 20% of training for validation
costs_per_turn_backtest: 0.0001
quality_halflife: 63  # ~3 month quality memory

# Portfolio construction
use_quality_memory: true
ensemble_method: "stability_weighted"  # Use stability scores for weighting
min_models_per_metric: 1
max_models_per_metric: 5

# Stability metrics - based on best individual test results
stability_metrics:
  - name: "Sharpe_Aggressive"
    metric_type: "sharpe"
    kwargs:
      costs_per_turn: 0.0001
    alpha: 1.0        # Full weight on validation performance
    lam_gap: 0.2      # Low stability penalty (allow some train-val gap)
    relative_gap: false
    top_k: 3          # Select top 3 models
    eta_quality: 0.1  # 10% weight on quality memory
    
  - name: "Sharpe_Conservative"
    metric_type: "sharpe"
    kwargs:
      costs_per_turn: 0.0001
    alpha: 0.8        # Slightly lower validation weight
    lam_gap: 0.4      # Higher stability penalty
    relative_gap: false
    top_k: 5          # More diversification
    eta_quality: 0.0  # No quality memory (pure stability)
    
  - name: "AdjSharpe_Balanced"
    metric_type: "adj_sharpe"
    kwargs:
      costs_per_turn: 0.0001
      lambda_to: 0.1  # Turnover penalty
    alpha: 1.0
    lam_gap: 0.3      # Moderate stability penalty
    relative_gap: false
    top_k: 4          # Balanced selection
    eta_quality: 0.05 # Light quality memory
    
  - name: "HitRate_Stable"
    metric_type: "hit_rate"
    kwargs: {}
    alpha: 0.9        # Emphasis on validation hit rate
    lam_gap: 0.2      # Lower penalty (hit rate is more stable)
    relative_gap: false
    top_k: 3          # Conservative selection
    eta_quality: 0.15 # Higher quality memory weight

# Output configuration
log_label: "best_stability_portfolio"
save_results: true
create_visualizations: true

# Notes on configuration choices:
#
# 1. Multiple metric types for diversification:
#    - Sharpe metrics for risk-adjusted returns
#    - Adjusted Sharpe for turnover control
#    - Hit Rate for directional accuracy
#
# 2. Varying stability parameters:
#    - Aggressive: Low lam_gap, quality memory for momentum
#    - Conservative: High lam_gap, no quality memory for pure stability
#    - Balanced: Moderate settings with light quality memory
#
# 3. Top-k selection:
#    - Range from 3-5 models per metric
#    - Balances diversification vs concentration
#
# 4. Quality memory (eta_quality):
#    - 0.0-0.15 range based on metric type
#    - Higher for less stable metrics (hit_rate)
#    - Lower/zero for stability-focused strategies