# Production Individual Target Testing Configuration
# Based on original parameter defaults with optimizations

target_symbol: "@AD#C"  # Override via CLI
symbols: "@ES#C,@NQ#C,@YM#C,@RTY#C,@TY#C,@US#C,@FV#C,@TU#C,@EU#C,@BP#C,@JY#C,@AD#C,@C#C,@S#C,@W#C,@LE#C,@GF#C,@HE#C,@KC#C,@SB#C,@CC#C,@CT#C,@BO#C,@SM#C,@VX#C"
start_date: "2021-01-01"
end_date: "2023-12-31"
signal_hour: 12
n_hours: 24
on_target_only: false  # Full universe mode
corr_threshold: 0.7

# Model ensemble configuration  
n_models: 50   # Original default
n_select: 12   # Original default
folds: 6       # Original default
use_multiprocessing: true

# Original parameter values (conservative)
z_win: 100           # Original default
beta_pre: 1.0        # Original default  
lambda_to: 0.05      # Original default
weight_budget: 80    # Original default
w_dapy: 1.0          # Original default
w_ir: 1.0            # Original default
diversity_penalty: 0.2  # Original default
pmax: 0.20           # Original default (much more restrictive!)
final_shuffles: 600  # Original default
block: 10            # Original default

# Training configuration
train_production: false
dapy_style: "hits"
test_start: "2023-10-01" 
random_train_pct: 0.0