# Systematic Objective Function Testing Configuration
# For EXPERIMENT_RESULTS_PART2.md Test 1a-1d series

# Optimal parameters from Part 1 experiments
n_models: 75  # Optimal from Step 5b
n_select: 12  # Standard selection count
folds: 6      # Optimal from Step 13
correlation_threshold: 0.7
max_features: 50  # Proven optimal from Step 2

# Long-term data parameters
on_target_only: false
standardize_features: true
start_date: "2015-01-01"  # 10-year test period
end_date: null
n_hours: 24
signal_hour: 12

# Test parameters
pmax: 0.05
bypass_pvalue_gating: true  # Faster for systematic testing
random_train_pct: 0.0
lambda_to: 0.0  # No turnover penalty for objective comparison

# Comprehensive symbol universe for features
symbols:
  - "@AD#C"
  - "@BP#C" 
  - "@EU#C"
  - "@JY#C"
  - "@ES#C"
  - "@NQ#C"
  - "@RTY#C"
  - "@C#C"
  - "@CT#C"
  - "@KW#C"
  - "@S#C"
  - "@SM#C"
  - "@W#C"
  - "@FV#C"
  - "@TY#C"
  - "@US#C"
  - "QBZ#C"
  - "QCL#C" 
  - "QGC#C"
  - "QHG#C"
  - "QNG#C"
  - "QPL#C"
  - "QRB#C"
  - "QSI#C"