# production_full_system.yaml - PRODUCTION DEPLOYMENT CONFIGURATION
# High-performance configuration for full system evaluation with comprehensive testing
# Uses 10-year full history and optimal model counts for maximum reliability
# Runtime: ~20-60 minutes depending on system

# Data Configuration (Full 10-Year Period)
target_symbol: "@ES#C"  # Override via CLI
symbols: "@ES#C,@NQ#C,@YM#C,@RTY#C,@TY#C,@US#C,@FV#C,@TU#C,@EU#C,@BP#C,@JY#C,@AD#C,@C#C,@S#C,@W#C,@LE#C,@GF#C,@HE#C,@KC#C,@SB#C,@CC#C,@CT#C,@BO#C,@SM#C,@VX#C"
start_date: "2015-01-01"  # Full 10-year history
end_date: "2025-08-01"
signal_hour: 12
n_hours: 24
on_target_only: false
corr_threshold: 0.7
max_features: 100    # Production feature count (optimal: 100 for diagnostics)

# Optimal Model Configuration (Validated Settings)
n_models: 75        # Optimal model count (+0.02 to +0.50 Sharpe improvement)
n_select: 20        # More models selected for robustness (unused in stability mode)
folds: 10           # More folds for 10-year period
use_multiprocessing: true

# Ensemble Method Selection
use_stability_ensemble: true  # Use stability instead of GROPE for production

# Production Stability Ensemble Parameters
stability:
  metric_name: "sharpe"              # Primary selection metric
  top_k: 8                           # Select more drivers for 10-year production
  alpha: 1.0                         # Full weight on validation performance
  lam_gap: 0.3                       # Moderate stability penalty
  relative_gap: false                # Use absolute gap penalty
  eta_quality: 0.0                   # No quality momentum (production stable)
  quality_halflife: 63               # Quality memory (~3 months)
  inner_val_frac: 0.2                # 20% inner validation split
  costs_per_turn: 0.0001             # Small transaction costs

# Signal Processing Parameters
z_win: 100
beta_pre: 1.0
lambda_to: 0.05
weight_budget: 200  # Higher budget for production
w_dapy: 1.0
w_ir: 1.0
diversity_penalty: 0.2
pmax: 0.10          # Slightly relaxed for production (10% significance)

# Comprehensive Statistical Testing
p_value_gating: null      # Recommended: bypass for speed (3x faster, identical performance)
final_shuffles: 1000      # More shuffles for robust p-values
block: 10

# Training Configuration
train_production: false
dapy_style: "hits"
test_start: "2018-01-01"
random_train_pct: 0.0

# Advanced Objective Configuration
driver_selection_objective:
  dapy:
    dapy_style: "hits"
    weight: 1.0
  information_ratio:
    weight: 1.0

grope_weight_objective:
  dapy:
    dapy_style: "hits" 
    weight: 1.0
  information_ratio:
    weight: 1.0