# Production Configuration  
# Runtime: ~10-20 minutes

# Data Configuration
target_symbol: "@ES#C"
symbols: null  # Use default symbols from symbols.yaml
start_date: null  # Auto-detect
end_date: null    # Auto-detect
signal_hour: 12
n_hours: 3
on_target_only: false  # Use full universe
max_features: null     # No limit
corr_threshold: 0.7

# Model Configuration (Original Production Defaults)
n_models: 50
n_select: 15
folds: 5
use_multiprocessing: true

# Signal Processing
z_win: 100
beta_pre: 1.0
lambda_to: 0.05

# Optimization (Original Defaults)
weight_budget: 200
w_dapy: 1.0
w_ir: 1.0
diversity_penalty: 0.2
pmax: 0.20
final_shuffles: 1000
block: 10

# Training Methods
train_production: false
dapy_style: "hits"
test_start: "2018-01-01"
random_train_pct: 0.0
randtrain_seed: 123