instrument_config:
  '@AD#C':
    basket: FX
    bloomberg: ADU5 Curncy
    description: AUSTRALIAN DOLLAR
    fraction: 4
    max_held: 20
    max_traded: 40
    multiplier: 100000
  '@BO#C':
    basket: AGS
    bloomberg: BOZ5 Comdty
    description: SOYBEAN OIL
    fraction: 7
    max_held: 27
    max_traded: 54
    multiplier: 600
  '@BP#C':
    basket: FX
    bloomberg: BPU5 Curncy
    description: BRITISH POUND
    fraction: 4
    max_held: 16
    max_traded: 32
    multiplier: 62500
  '@C#C':
    basket: AGS
    bloomberg: C Z5 Comdty
    description: CORN
    fraction: 7
    max_held: 30
    max_traded: 60
    multiplier: 50
  '@CT#C':
    basket: AGS
    bloomberg: CTZ5 Comdty
    description: COTTON
    fraction: 7
    max_held: 22
    max_traded: 44
    multiplier: 500
  '@ES#C':
    basket: EQUITY
    bloomberg: ESU5 Index
    description: E-MINI S&P 500
    fraction: 3
    max_held: 11
    max_traded: 22
    multiplier: 50
  '@EU#C':
    basket: FX
    bloomberg: ECU5 Curncy
    description: EURO FX
    fraction: 4
    max_held: 10
    max_traded: 20
    multiplier: 125000
  '@FV#C':
    basket: RATESUS
    bloomberg: FVZ5 Comdty
    description: 5 YR US TREASURY NOTE
    fraction: 3
    max_held: 37
    max_traded: 74
    multiplier: 1000
  '@JY#C':
    basket: FX
    bloomberg: JYU5 Curncy
    description: JAPANESE YEN
    fraction: 4
    max_held: 15
    max_traded: 30
    multiplier: 12500000
  '@KW#C':
    basket: AGS
    bloomberg: KWZ5 Comdty
    description: HARD RED WINTER WHEAT
    fraction: 7
    max_held: 0
    max_traded: 0
    multiplier: 50
  '@NQ#C':
    basket: EQUITY
    bloomberg: NQU5 Index
    description: E-MINI NASDAQ 100
    fraction: 3
    max_held: 8
    max_traded: 16
    multiplier: 20
  '@RTY#C':
    basket: EQUITY
    bloomberg: RTYU5 Index
    description: E-MINI RUSSELL 2000
    fraction: 3
    max_held: 31
    max_traded: 62
    multiplier: 50
  '@S#C':
    basket: AGS
    bloomberg: S X5 Comdty
    description: SOYBEANS
    fraction: 7
    max_held: 14
    max_traded: 28
    multiplier: 50
  '@SM#C':
    basket: AGS
    bloomberg: SMZ5 Comdty
    description: SOYBEAN MEAL
    fraction: 7
    max_held: 24
    max_traded: 48
    multiplier: 100
  '@TY#C':
    basket: RATESUS
    bloomberg: TYZ5 Comdty
    description: 10 YR US TREASURY NOTE
    fraction: 3
    max_held: 36
    max_traded: 72
    multiplier: 1000
  '@US#C':
    basket: RATESUS
    bloomberg: USZ5 Comdty
    description: US LONG BOND
    fraction: 3
    max_held: 34
    max_traded: 68
    multiplier: 1000
  '@W#C':
    basket: AGS
    bloomberg: W Z5 Comdty
    description: WHEAT
    fraction: 7
    max_held: 26
    max_traded: 52
    multiplier: 50
  BD#C:
    basket: RATESEU
    bloomberg: RXU5 Comdty
    description: EURO BUND
    fraction: 2
    max_held: 30
    max_traded: 60
    multiplier: 1000
  BL#C:
    basket: RATESEU
    bloomberg: OEU5 Comdty
    description: EURO BUND
    fraction: 2
    max_held: 34
    max_traded: 68
    multiplier: 1000
  QBZ#C:
    basket: Energy
    bloomberg: COV5 Comdty
    description: BRENT CRUDE OIL
    fraction: 4
    max_held: 17
    max_traded: 0
    multiplier: 1000
  QCL#C:
    basket: Energy
    bloomberg: CLV5 Comdty
    description: CRUDE OIL
    fraction: 4
    max_held: 18
    max_traded: 36
    multiplier: 1000
  QGC#C:
    basket: METALS
    bloomberg: GCZ5 Comdty
    description: GOLD
    fraction: 4
    max_held: 4
    max_traded: 8
    multiplier: 100
  QHG#C:
    basket: METALS
    bloomberg: HGZ5 Comdty
    description: COPPER
    fraction: 4
    max_held: 11
    max_traded: 22
    multiplier: 25000
  QNG#C:
    basket: Energy
    bloomberg: NGV25 Comdty
    description: NATURAL GAS
    fraction: 4
    max_held: 10
    max_traded: 30
    multiplier: 10000
  QPL#C:
    basket: METALS
    bloomberg: PLV5 Comdty
    description: PLATINUM
    fraction: 4
    max_held: 26
    max_traded: 52
    multiplier: 50
  QRB#C:
    basket: Energy
    bloomberg: XBV5 Comdty
    description: RBOB GASOLINE
    fraction: 4
    max_held: 13
    max_traded: 0
    multiplier: 42000
  QSI#C:
    basket: METALS
    bloomberg: SIZ5 Comdty
    description: SILVER
    fraction: 4
    max_held: 8
    max_traded: 16
    multiplier: 5000

portfolio_config:
  total_aum: 50000000
  allocations:
    AGS: 2500000
    Energy: 5000000
    EQUITY: 10000000
    FX: 5000000
    METALS: 5000000
    RATESEU: 8000000
    RATESUS: 12000000

current_positions:
  '@ES#C': 0


s3:
  trades_bucket: "sydney-quant-signals-v2/trades"
  logs_bucket: "sydney-quant-signals-v2/logs"